### ISSUE TITLE
pfampipeline.py CANNOT FIND FILE

### ISSUE THREAD

**Issue by mezoderma** [wrf/genomeGTFtools#12]
Hi,

i tried to use pfampipeline.py, and got this message:

```
ilya@ilya-MacBookAir:~/genomeGTFtools$ ./pfampipeline.py test_data/nidogen_full_prots.fasta 
ERROR: CANNOT FIND FILE test_data/nidogen_full_prots.fasta
```

All dependencies are setted (Bio Python, HMMER et al) and the input is present, sure:

```
ilya@ilya-MacBookAir:~/genomeGTFtools$ ls test_data/ -l nidogen*
-rw-rw-r-- 1 ilya ilya 13333 ноя  4 14:53 nidogen_full_prots.fasta

```
Checked at laptop Ubuntu 20.04 and server CentOS 7 - looks the same.

Could you help me please?

Thank you in advance,
Ilya

**Comment by wrf** [comment]
Hi Ilya,
This was a bug in the code that it reports the wrong missing file. You may need the clan links file, should be here:
ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.clans.tsv.gz
This is needed for a step that combines similar domains into clans, e.g. Ig domains, VWF, etc
Best
Warren

**Comment by mezoderma** [comment]
> Hi Ilya,
> This was a bug in the code that it reports the wrong missing file. You may need the clan links file, should be here:
> ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.clans.tsv.gz
> This is needed for a step that combines similar domains into clans, e.g. Ig domains, VWF, etc
> Best
> Warren

**Comment by mezoderma** [comment]
Thank you, Warren, it resolve the trouble!

But after fix it I found another error:

```
ilya@ilya-MacBookAir:~/genomeGTFtools$ ./pfampipeline.py -P /media/ilya/7A12069F1206608D/pfam/Pfam-A.hmm test_data/nidogen_full_prots.fasta 
# Searching PFAM against test_data/nidogen_full_prots.fasta  Thu Nov  5 00:12:01 2020
Calling:
hmmscan --cpu 1 --domtblout test_data/nidogen_full_prots.pfam.tab /media/ilya/7A12069F1206608D/pfam/Pfam-A.hmm test_data/nidogen_full_prots.fasta
Calling:
./pfam2gff.py -i test_data/nidogen_full_prots.pfam.tab -e 0.1
# Parsing hmmscan PFAM tabular test_data/nidogen_full_prots.pfam.tab  Thu Nov  5 00:12:28 2020
# Found 911 domains for 9 proteins  Thu Nov  5 00:12:28 2020
# Removed 31 domain hits by shortness
# Removed 165 domain hits by evalue
Calling:
./pfamgff2clans.py -i test_data/nidogen_full_prots.pfam.gff -c /home/ilya/db/Pfam-A.clans.tsv -s test_data/nidogen_full_prots.fasta
# Parsing clan links from /home/ilya/db/Pfam-A.clans.tsv  Thu Nov  5 00:12:28 2020
# Found 7165 clan links  Thu Nov  5 00:12:28 2020
# Parsing proteins from test_data/nidogen_full_prots.fastaThu Nov  5 00:12:28 2020
# Parsing GTF from test_data/nidogen_full_prots.pfam.gff  Thu Nov  5 00:12:28 2020
# Found 676 domains for 9 proteinsThu Nov  5 00:12:28 2020
# Coverting domains to clansThu Nov  5 00:12:28 2020
Traceback (most recent call last):
  File "./pfamgff2clans.py", line 143, in <module>
    main(sys.argv[1:],sys.stdout)
  File "./pfamgff2clans.py", line 140, in main
    convert_domains(domainsbyprot, args.program, args.type, wayout, pfamtoclandict, pfamannot, seqlens)
  File "./pfamgff2clans.py", line 93, in convert_domains
    iterprots = fastalendict.iterkeys()
AttributeError: 'collections.OrderedDict' object has no attribute 'iterkeys'
Calling:
Rscript ./draw_protein_gtf.R test_data/nidogen_full_prots.clan.gff
Error in read.table(inputfile, header = FALSE, sep = "\t") :
  no lines in stdin
Terminated
```
I checked the file nidogen_full_prots.clan.gff and it is empty:

```
ilya@ilya-MacBookAir:~/genomeGTFtools$ ls -l nidogen_full_prots.clan.gff
-rw-rw-r-- 1 ilya ilya 0 ноя  4 23:39 nidogen_full_prots.clan.gff

```

So it's look like the pfamgff2clans.py doesn't works, and I tried to run it separately of pipeline:

```
ilya@ilya-MacBookAir:~/genomeGTFtools$ ./pfamgff2clans.py -i nidogen_full_prots.pfam.gtf -c ~/db/Pfam-A.clans.tsv > nidogen_full_prots.clan.gtf
# Parsing clan links from /home/ilya/db/Pfam-A.clans.tsv  Thu Nov  5 00:15:40 2020
# Found 7165 clan links  Thu Nov  5 00:15:40 2020
# Parsing GTF from nidogen_full_prots.pfam.gtf  Thu Nov  5 00:15:40 2020
# Found 676 domains for 9 proteinsThu Nov  5 00:15:40 2020
# Coverting domains to clansThu Nov  5 00:15:40 2020
Traceback (most recent call last):
  File "./pfamgff2clans.py", line 143, in <module>
    main(sys.argv[1:],sys.stdout)
  File "./pfamgff2clans.py", line 140, in main
    convert_domains(domainsbyprot, args.program, args.type, wayout, pfamtoclandict, pfamannot, seqlens)
  File "./pfamgff2clans.py", line 95, in convert_domains
    iterprots = domainsbyprot.iterkeys()
AttributeError: 'collections.defaultdict' object has no attribute 'iterkeys'

```

Sorry, I can't interpret error regarding to attributes. Could you help, please?

**Comment by wrf** [comment]
looks like a python2 to python3 error, since iterkeys() no longer exists.
I just sent an update, can you please try it again?

**Comment by mezoderma** [comment]
Cool, it works!
Thank you very much, Warren! )
