### ISSUE TITLE
pfampipeline.py: FileNotFoundError: [Errno 2]

### ISSUE THREAD

**Issue by mezoderma** [wrf/genomeGTFtools#14]
Hi Warren,

I run the pfampipeline.py, and got a message that pfam2gff.py does not found:

```
ilya@ilya-MacBookAir:~/genomeGTFtools$ ./pfampipeline.py -P ~/pfam_base/Pfam-A.hmm ./test_data/nidogen_full_prots.fasta 
# Searching PFAM against ./test_data/nidogen_full_prots.fasta  Tue Feb  2 15:31:37 2021
Calling:
hmmscan --cpu 1 --domtblout ./test_data/nidogen_full_prots.pfam.tab /home/ilya/pfam_base/Pfam-A.hmm ./test_data/nidogen_full_prots.fasta
Calling:
pfam2gff.py -i ./test_data/nidogen_full_prots.pfam.tab -e 0.1
Traceback (most recent call last):
  File "./pfampipeline.py", line 120, in <module>
    main(sys.argv[1:],sys.stdout)
  File "./pfampipeline.py", line 112, in main
    pfamgff = call_pfamgff(hmmtblout, args.evalue)
  File "./pfampipeline.py", line 51, in call_pfamgff
    subprocess.call(pfam2gff_args, stdout=pfamgff)
  File "/usr/lib/python3.8/subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pfam2gff.py'
```

But actually it is present:

```
ilya@ilya-MacBookAir:~/genomeGTFtools$ ls pfam* -lh
-rwxrwxr-x 1 ilya ilya  17K фев  2 15:31 pfam2gff.py
-rwxrwxr-x 1 ilya ilya 5,9K фев  2 15:31 pfamgff2clans.py
-rwxrwxr-x 1 ilya ilya 5,6K фев  2 15:13 pfampipeline.py
```

And even works if I run it separately:

```
ilya@ilya-MacBookAir:~/genomeGTFtools$ ./pfam2gff.py -i ./test_data/nidogen_full_prots.pfam.tab -e 0.1
# Parsing hmmscan PFAM tabular ./test_data/nidogen_full_prots.pfam.tab  Tue Feb  2 15:24:41 2021
# Found 911 domains for 9 proteins  Tue Feb  2 15:24:41 2021
# Removed 31 domain hits by shortness
# Removed 165 domain hits by evalue
NID1_MOUSE	hmmscan	PFAM	176	266	78.9	.	.	ID=PF06119.NIDO.1;Name=PF06119.NIDO.1
NID1_MOUSE	hmmscan	PFAM	388	419	14.3	.	.	ID=PF00008.EGF.1;Name=PF00008.EGF.1
NID1_MOUSE	hmmscan	PFAM	388	423	5.3	.	.	ID=PF07645.EGF_CA.1;Name=PF07645.EGF_CA.1
NID1_MOUSE	hmmscan	PFAM	388	424	4.2	.	.	ID=PF12946.EGF_MSP1_1.1;Name=PF12946.EGF_MSP1_1.1
NID1_MOUSE	hmmscan	PFAM	427	619	240.2	.	.	ID=PF07474.G2F.1;Name=PF07474.G2F.1
NID1_MOUSE	hmmscan	PFAM	669	706	8.6	.	.	ID=PF07645.EGF_CA.2;Name=PF07645.EGF_CA.2
NID1_MOUSE	hmmscan	PFAM	670	702	15.9	.	.	ID=PF00008.EGF.2;Name=PF00008.EGF.2
NID1_MOUSE	hmmscan	PFAM	670	706	8.0	.	.	ID=PF14670.FXa_inhibition.2;Name=PF14670.FXa_inhibition.2
NID1_MOUSE	hmmscan	PFAM	676	706	8.6	.	.	ID=PF12946.EGF_MSP1_1.2;Name=PF12946.EGF_MSP1_1.2
```

Could you please help me? What is the trouble with pfampipeline.py?

Ilya

**Comment by wrf** [comment]
Hi Ilya,
I'm really not sure, it might be changes to subprocess that occurred after v3.5 (which I am still using). For the moment, the test data command still works normally for me.
Did it work for you in when you had submitted the previous error?
Warren

**Comment by mezoderma** [comment]
Hi Warren,

Sorry for delay. This trouble occured after we update Python indeed, and now I have 3.8.2 and 3.8.5 versions at separete machines, and this error presents at the both.
The previous error was resolved with clan links file and update of your script for python3, thank you.

Do you suppose to goes back to 3.5 version?
Ilya
