### ISSUE TITLE
TypeError: unsupported operand

### ISSUE THREAD

**Issue by mictadlo** [wrf/genomeGTFtools#4]
Hi,
I ran into the below error:

```
> python stringtie_gtf_to_gff3.py bams/stringtie_merged.gtf > bams/stringtie_merged.gff3
Traceback (most recent call last):
  File "/work/apps/genomeGTFtools/misc/stringtie_gtf_to_gff3.py", line 41, in <module>
    main(sys.argv[1:],sys.stdout)
  File "/work/apps/genomeGTFtools/misc/stringtie_gtf_to_gff3.py", line 21, in main
    print >> sys.stderr, "# Converting {} to GFF".format(args.gtf)
TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'. Did you mean "print(<message>, file=<output_stream>)"?
```
with this gtf file:

```
# stringtie --merge -p 8 -o bams/stringtie_merged.gtf bams/mergelist.txt
# StringTie version 2.0
NbV1Ch01        StringTie       transcript      221937  223251  1000    -       .       gene_id "MSTRG.1"; transcript_id "MSTRG.1.1"; 
NbV1Ch01        StringTie       exon    221937  222881  1000    -       .       gene_id "MSTRG.1"; transcript_id "MSTRG.1.1"; exon_number "1"; 
NbV1Ch01        StringTie       exon    222989  223251  1000    -       .       gene_id "MSTRG.1"; transcript_id "MSTRG.1.1"; exon_number "2"; 
NbV1Ch01        StringTie       transcript      773600  784171  1000    -       .       gene_id "MSTRG.2"; transcript_id "MSTRG.2.1"; 
NbV1Ch01        StringTie       exon    773600  773945  1000    -       .       gene_id "MSTRG.2"; transcript_id "MSTRG.2.1"; exon_number "1"; 
NbV1Ch01        StringTie       exon    774033  774173  1000    -       .       gene_id "MSTRG.2"; transcript_id "MSTRG.2.1"; exon_number "2"; 
NbV1Ch01        StringTie       exon    783756  784171  1000    -       .       gene_id "MSTRG.2"; transcript_id "MSTRG.2.1"; exon_number "3"; 
NbV1Ch01        StringTie       transcript      1003303 1005419 1000    -       .       gene_id "MSTRG.3"; transcript_id "MSTRG.3.1"; 
NbV1Ch01        StringTie       exon    1003303 1003738 1000    -       .       gene_id "MSTRG.3"; transcript_id "MSTRG.3.1"; exon_number "1"; 
NbV1Ch01        StringTie       exon    1004949 1005419 1000    -       .       gene_id "MSTRG.3"; transcript_id "MSTRG.3.1"; exon_number "2"; 
NbV1Ch01        StringTie       transcript      918382  942103  1000    +       .       gene_id "MSTRG.4"; transcript_id "MSTRG.4.1"; 
NbV1Ch01        StringTie       exon    918382  918907  1000    +       .       gene_id "MSTRG.4"; transcript_id "MSTRG.4.1"; exon_number "1"; 
NbV1Ch01        StringTie       exon    919974  920080  1000    +       .       gene_id "MSTRG.4"; transcript_id "MSTRG.4.1"; exon_number "2"; 
NbV1Ch01        StringTie       exon    921381  921508  1000    +       .       gene_id "MSTRG.4"; transcript_id "MSTRG.4.1"; exon_number "3"; 
NbV1Ch01        StringTie       exon    923908  923979  1000    +       .       gene_id "MSTRG.4"; transcript_id "MSTRG.4.1"; exon_number "4"; 
NbV1Ch01        StringTie       exon    928187  928288  1000    +       .       gene_id "MSTRG.4"; transcript_id "MSTRG.4.1"; exon_number "5"; 
NbV1Ch01        StringTie       exon    933546  933605  1000    +       .       gene_id "MSTRG.4"; transcript_id "MSTRG.4.1"; exon_number "6"; 
NbV1Ch01        StringTie       exon    937393  937458  1000    +       .       gene_id "MSTRG.4"; transcript_id "MSTRG.4.1"; exon_number "7"; 
NbV1Ch01        StringTie       exon    938672  938719  1000    +       .       gene_id "MSTRG.4"; transcript_id "MSTRG.4.1"; exon_number "8"; 
NbV1Ch01        StringTie       exon    939217  939393  1000    +       .       gene_id "MSTRG.4"; transcript_id "MSTRG.4.1"; exon_number "9"; 
NbV1Ch01        StringTie       exon    939484  939539  1000    +       .       gene_id "MSTRG.4"; transcript_id "MSTRG.4.1"; exon_number "10"; 
NbV1Ch01        StringTie       exon    939630  939747  1000    +       .       gene_id "MSTRG.4"; transcript_id "MSTRG.4.1"; exon_number "11"; 
NbV1Ch01        StringTie       exon    940011  940100  1000    +       .       gene_id "MSTRG.4"; transcript_id "MSTRG.4.1"; exon_number "12"; 
NbV1Ch01        StringTie       exon    941276  941385  1000    +       .       gene_id "MSTRG.4"; transcript_id "MSTRG.4.1"; exon_number "13"; 
NbV1Ch01        StringTie       exon    941521  942103  1000    +       .       gene_id "MSTRG.4"; transcript_id "MSTRG.4.1"; exon_number "14"; 
```
How is it possible to fix it?

Thank you in advance,

Michal

**Comment by wrf** [comment]
This is possibly a python2/3 incompatibility. I think that the print and sys.write are not the same between the two versions.
These scripts were all python2, and I need to update them all in the next few months to python3, since 2 is no longer supported after this year.

Meanwhile, you can check if you have both in parallel (many systems do), in the shell would be something like this, and you would see binaries for python2 and python3

`ls /usr/bin/python* -l`

if you do have both, I think you can declare to explicitly use python2 by changing the first line to:

`#!/usr/bin/env python2`

Let me know if that works.
